class Item:
    item_id: int
    group: int
    index: int
    name: str
    two_handed: bool
    drop_level: int
    sizeX: int
    sizeY: int
    damage_min: int
    damage_max: int
    defence_rate: int
    defence: int
    attack_speed: int
    move_speed: int
    durability: int
    raise_what: bool
    require_strength: int
    require_agility: int
    require_energy: int
    require_level: int
    value_what: int
    dw_allowed: bool
    dk_allowed: bool
    elf_allowed: bool
    mg_allowed: bool
    ice_attribute: bool
    poison_attribute: bool
    lightning_attribute: bool
    fire_attribute: bool
